// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: create_work.sql

package sqlc

import (
	"context"
)

const maybeCreateWork = `-- name: MaybeCreateWork :exec

INSERT OR IGNORE INTO work_queue (domain, project, data) VALUES (?1, ?2, ?3)
`

type MaybeCreateWorkParams struct {
	Domain  string
	Project string
	Data    []byte
}

// MaybeCreateWork inserts work into a work queue.
func (q *Queries) MaybeCreateWork(ctx context.Context, arg MaybeCreateWorkParams) error {
	_, err := q.db.ExecContext(ctx, maybeCreateWork, arg.Domain, arg.Project, arg.Data)
	return err
}
