// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: error_work.sql

package sqlc

import (
	"context"
)

const errorWork = `-- name: ErrorWork :exec

UPDATE work_queue
SET status = 'done', error=?1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
`

type ErrorWorkParams struct {
	Error string
	ID    int64
}

// ErrorWork fetches a single book.
func (q *Queries) ErrorWork(ctx context.Context, arg ErrorWorkParams) error {
	_, err := q.db.ExecContext(ctx, errorWork, arg.Error, arg.ID)
	return err
}
