// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: finish_work.sql

package sqlc

import (
	"context"
)

const finishWork = `-- name: FinishWork :one

UPDATE work_queue
SET status = 'done', updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING data
`

// FinishWork fetches a single book.
func (q *Queries) FinishWork(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, finishWork, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}
