// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_work.sql

package sqlc

import (
	"context"
)

const getWork = `-- name: GetWork :one

SELECT id, status
FROM work_queue
WHERE domain=?1 AND project=?2 AND status!=?3
`

type GetWorkParams struct {
	Domain  string
	Project string
	Status  string
}

type GetWorkRow struct {
	ID     int64
	Status string
}

// GetWork fetches a single book.
func (q *Queries) GetWork(ctx context.Context, arg GetWorkParams) (GetWorkRow, error) {
	row := q.db.QueryRowContext(ctx, getWork, arg.Domain, arg.Project, arg.Status)
	var i GetWorkRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}
