// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type WorkQueue struct {
	CreatedAt time.Time
	Data      []byte
	Domain    string
	ID        int64
	Project   string
	Status    string
	UpdatedAt time.Time
	Error     string
}
