// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: postprocess_work.sql

package sqlc

import (
	"context"
)

const postprocessWork = `-- name: PostprocessWork :one

UPDATE work_queue
SET status = 'postprocessing', updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING data
`

// PostprocessWork fetches a single book.
func (q *Queries) PostprocessWork(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, postprocessWork, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}
