baseURL = 'http://localhost:11080'
languageCode = 'en-us'
title = 'Autodemo'
theme = 'terminal'

[params]
  contentTypeName = "pages"
  showMenuItems = 0

[languages]
  [languages.en]
    title = "Autodemo Proxy"
    subtitle = "Generate Video Demos Automagically"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Autodemo"
      logoHomeLink = "/pages/dashboard"
